name: K8s apps

on:
  push:
    branches:
    - main
    paths:
    - manifests/**
  workflow_dispatch:

jobs:
  dev:
    environment: Dev
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Update kube resources
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: apply -f manifests/dev
  prod:
    environment: Prod
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Update kube resources
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: apply -f manifests/prod
