name: K8S

on:
  push:
    branches:
    - main
    paths:
    - manifests/**
  workflow_dispatch:


jobs:
  kube:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Update kube resources
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: apply -f manifests
