name: K8s Env

on:
  push:
    branches:
    - main
    paths:
    - cluster-do/**
    - manifests/ingress-controller.yaml
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./cluster-do

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
    
    - name: Terraform Plan
      env:
        TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
        TF_VAR_region: nyc1
        TF_VAR_project_name: safeops-challenge-cluster
        TF_VAR_min_nodes: 1
        TF_VAR_max_nodes: 3
        TF_VAR_machine_size: s-2vcpu-2gb
        TF_VAR_registry_password: ${{ secrets.REGISTRY_PASSWORD }}
        TF_VAR_email: marteomasoyyo@gmail.com
        TF_VAR_registry_name: safeops-challenge
      run: terraform plan -input=false



  apply:
    environment: Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./cluster-do

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply 
      env:
        TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
        TF_VAR_region: nyc1
        TF_VAR_project_name: safeops-challenge-cluster
        TF_VAR_min_nodes: 1
        TF_VAR_max_nodes: 3
        TF_VAR_machine_size: s-2vcpu-2gb
        TF_VAR_registry_password: ${{ secrets.REGISTRY_PASSWORD }}
        TF_VAR_email: marteomasoyyo@gmail.com
        TF_VAR_registry_name: safeops-challenge
      run: terraform apply -auto-approve -input=false

    - name: Debug
      run: ls ../manifests
      
    - name: K8s Ingress
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: apply -f ../manifests/ingress-controller.yaml